export const DESIGN_PRESETS = {
  'ats-safe': {
    name: 'ATS Safe',
    descriptionKey: 'preset.atsSafeDesc',
    settings: {
      fontFamily: 'Arial',
      fontSize: 'md',
      lineHeight: 'normal',
      margins: 'normal',
      density: 'balanced',
      headingStyle: 'standard',
      showSectionDividers: true,
      itemSpacing: 'normal',
      paragraphSpacing: 'normal',
      contactLayout: 'inline',
      skillsPresentation: 'list',
      dateAlignment: 'opposite',
      showBulletPoints: true,
    },
  },
  'modern-professional': {
    name: 'Modern Professional',
    descriptionKey: 'preset.modernProfessionalDesc',
    settings: {
      fontFamily: 'Inter',
      fontSize: 'md',
      lineHeight: 'relaxed',
      margins: 'normal',
      density: 'comfortable',
      headingStyle: 'prominent',
      showSectionDividers: false,
      itemSpacing: 'relaxed',
      paragraphSpacing: 'relaxed',
      contactLayout: 'stacked',
      skillsPresentation: 'grouped',
      dateAlignment: 'opposite',
      showBulletPoints: true,
    },
  },
  'compact-one-page': {
    name: 'Compact One-Page',
    descriptionKey: 'preset.compactOnePageDesc',
    settings: {
      fontFamily: 'Roboto',
      fontSize: 'md',
      lineHeight: 'tight',
      margins: 'compact',
      density: 'compact',
      headingStyle: 'understated',
      showSectionDividers: true,
      itemSpacing: 'tight',
      paragraphSpacing: 'tight',
      contactLayout: 'inline',
      skillsPresentation: 'inline',
      dateAlignment: 'inline',
      showBulletPoints: true,
    },
  },
  'executive-focus': {
    name: 'Executive Focus',
    descriptionKey: 'preset.executiveFocusDesc',
    settings: {
      fontFamily: 'Georgia',
      fontSize: 'lg',
      lineHeight: 'normal',
      margins: 'spacious',
      density: 'comfortable',
      headingStyle: 'prominent',
      showSectionDividers: true,
      itemSpacing: 'normal',
      paragraphSpacing: 'relaxed',
      contactLayout: 'inline',
      skillsPresentation: 'list',
      dateAlignment: 'opposite',
      showBulletPoints: true,
    },
  },
  'developer-focus': {
    name: 'Developer Focus',
    descriptionKey: 'preset.developerFocusDesc',
    settings: {
      fontFamily: 'Fira Code',
      fontSize: 'sm',
      lineHeight: 'normal',
      margins: 'normal',
      density: 'compact',
      headingStyle: 'standard',
      showSectionDividers: false,
      itemSpacing: 'normal',
      paragraphSpacing: 'tight',
      contactLayout: 'stacked',
      skillsPresentation: 'grouped',
      dateAlignment: 'opposite',
      showBulletPoints: true,
    },
  },
  'minimal-print': {
    name: 'Minimal Print',
    descriptionKey: 'preset.minimalPrintDesc',
    settings: {
      fontFamily: 'Helvetica',
      fontSize: 'md',
      lineHeight: 'tight',
      margins: 'normal',
      density: 'balanced',
      headingStyle: 'understated',
      showSectionDividers: false,
      itemSpacing: 'tight',
      paragraphSpacing: 'tight',
      contactLayout: 'inline',
      skillsPresentation: 'list',
      dateAlignment: 'opposite',
      showBulletPoints: false,
    },
  },
};

export function getPresetSettings(presetId) {
  const preset = DESIGN_PRESETS[presetId];
  return preset ? preset.settings : null;
}
